---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian
    image: 'alesauce/debian-ansible-testing-frankenstein:latest'
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
